services:
  migration:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./entrypoint.sh migrate
    profiles: ["manual"]
    env_file:
      - '.env'
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./entrypoint.sh api
    container_name: talent-mobility-api
    tty: true
    stdin_open: true
    ports:
      - "${APP_PORT:-4004}:${APP_PORT:-4004}"
    env_file:
      - '.env'
    environment:
      UVICORN_RELOAD: "true"
    depends_on:
      - redis
    volumes:
      - ./:/code
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./entrypoint.sh worker
    container_name: talent-mobility-worker
    env_file:
      - '.env'
    environment:
      WORKER_RELOAD: "true"
    depends_on:
      - redis
    volumes:
      - ./:/code
  redis:
    image: "redis:alpine"
