[pytest]
asyncio_mode=auto
addopts = -m "not benchmark"
env =
    LOG_LEVEL=DEBUG
    APP_ENV=test
filterwarnings =
    ignore::DeprecationWarning
markers =
    benchmark: mark test as benchmark (excluded from unit tests)
